// Code is generated by Telerik Data Access Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;
using BanditsModel;

namespace Bandits
{
	public partial class GuardianRepository : OpenAccessBaseRepository<BanditsModel.Guardian, BanditsModel.BanditsModel>
    {
	
    }

	public partial class GuardianTypeRepository : OpenAccessBaseRepository<BanditsModel.GuardianType, BanditsModel.BanditsModel>
    {
	
    }

	public partial class PersonRepository : OpenAccessBaseRepository<BanditsModel.Person, BanditsModel.BanditsModel>
    {
	
    }

	public partial class PlayerRepository : OpenAccessBaseRepository<BanditsModel.Player, BanditsModel.BanditsModel>
    {
	
    }

	public partial class ProgramRepository : OpenAccessBaseRepository<BanditsModel.Program, BanditsModel.BanditsModel>
    {
	
    }

	public partial class TeamRepository : OpenAccessBaseRepository<BanditsModel.Team, BanditsModel.BanditsModel>
    {
	
    }

	public partial class TeamPlayerRepository : OpenAccessBaseRepository<BanditsModel.TeamPlayer, BanditsModel.BanditsModel>
    {
	
    }

	public partial class UserRoleRepository : OpenAccessBaseRepository<BanditsModel.UserRole, BanditsModel.BanditsModel>
    {
	
    }

	public partial class WebUserRepository : OpenAccessBaseRepository<BanditsModel.WebUser, BanditsModel.BanditsModel>
    {
	
    }

}
