#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BanditsModel;

namespace BanditsModel	
{
	public partial class Auth_RoleAssignment
	{
		private int _roleAssignmentId;
		public virtual int RoleAssignmentId
		{
			get
			{
				return this._roleAssignmentId;
			}
			set
			{
				this._roleAssignmentId = value;
			}
		}
		
		private Auth_Role _auth_Role;
		public virtual Auth_Role Role
		{
			get
			{
				return this._auth_Role;
			}
			set
			{
				this._auth_Role = value;
			}
		}
		
		private IList<Auth_ScopeAssignment> _auth_ScopeAssignments = new List<Auth_ScopeAssignment>();
		public virtual IList<Auth_ScopeAssignment> ScopeAssignments
		{
			get
			{
				return this._auth_ScopeAssignments;
			}
		}
		
		private IList<Auth_Permission> _auth_Permissions = new List<Auth_Permission>();
		public virtual IList<Auth_Permission> Permissions
		{
			get
			{
				return this._auth_Permissions;
			}
		}
		
	}
}
#pragma warning restore 1591
