#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BanditsModel;

namespace BanditsModel	
{
	public partial class Auth_ScopeAssignment
	{
		private int _scopeAssignmentId;
		public virtual int ScopeAssignmentId
		{
			get
			{
				return this._scopeAssignmentId;
			}
			set
			{
				this._scopeAssignmentId = value;
			}
		}
		
		private long _resourceId;
		public virtual long ResourceId
		{
			get
			{
				return this._resourceId;
			}
			set
			{
				this._resourceId = value;
			}
		}
		
		private bool _deny;
		public virtual bool Deny
		{
			get
			{
				return this._deny;
			}
			set
			{
				this._deny = value;
			}
		}
		
		private Auth_Scope _auth_Scope;
		public virtual Auth_Scope Scope
		{
			get
			{
				return this._auth_Scope;
			}
			set
			{
				this._auth_Scope = value;
			}
		}
		
	}
}
#pragma warning restore 1591
