#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BanditsModel;

namespace BanditsModel	
{
	public partial class Person
	{
		private int _personId;
		public virtual int PersonId
		{
			get
			{
				return this._personId;
			}
			set
			{
				this._personId = value;
			}
		}
		
		private string _fName;
		public virtual string FName
		{
			get
			{
				return this._fName;
			}
			set
			{
				this._fName = value;
			}
		}
		
		private string _lName;
		public virtual string LName
		{
			get
			{
				return this._lName;
			}
			set
			{
				this._lName = value;
			}
		}
		
		private System.Nullable<System.Char> _mInitial;
		public virtual System.Nullable<System.Char> MInitial
		{
			get
			{
				return this._mInitial;
			}
			set
			{
				this._mInitial = value;
			}
		}
		
		private System.Nullable<System.Char> _gender;
		public virtual System.Nullable<System.Char> Gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				this._gender = value;
			}
		}
		
		private DateTime? _dOB;
		public virtual DateTime? DOB
		{
			get
			{
				return this._dOB;
			}
			set
			{
				this._dOB = value;
			}
		}
		
		private DateTime _createDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private DateTime? _modifyDate;
		public virtual DateTime? ModifyDate
		{
			get
			{
				return this._modifyDate;
			}
			set
			{
				this._modifyDate = value;
			}
		}
		
		private bool _isDeleted;
		public virtual bool IsDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				this._isDeleted = value;
			}
		}
		
		private WebUser _createUser;
		public virtual WebUser CreateUser
		{
			get
			{
				return this._createUser;
			}
			set
			{
				this._createUser = value;
			}
		}
		
		private WebUser _modifyUser;
		public virtual WebUser ModifyUser
		{
			get
			{
				return this._modifyUser;
			}
			set
			{
				this._modifyUser = value;
			}
		}
		
	}
}
#pragma warning restore 1591
