#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BanditsModel;

namespace BanditsModel	
{
	public partial class Team
	{
		private int _teamId;
		public virtual int TeamId
		{
			get
			{
				return this._teamId;
			}
			set
			{
				this._teamId = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private DateTime _minDOB;
		public virtual DateTime MinDOB
		{
			get
			{
				return this._minDOB;
			}
			set
			{
				this._minDOB = value;
			}
		}
		
		private DateTime _maxDOB;
		public virtual DateTime MaxDOB
		{
			get
			{
				return this._maxDOB;
			}
			set
			{
				this._maxDOB = value;
			}
		}
		
		private DateTime _startDate;
		public virtual DateTime StartDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				this._startDate = value;
			}
		}
		
		private DateTime _endDate;
		public virtual DateTime EndDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				this._endDate = value;
			}
		}
		
		private Program _program;
		public virtual Program Program
		{
			get
			{
				return this._program;
			}
			set
			{
				this._program = value;
			}
		}
		
		private IList<TeamPlayer> _teamPlayers = new List<TeamPlayer>();
		public virtual IList<TeamPlayer> Roster
		{
			get
			{
				return this._teamPlayers;
			}
		}
		
	}
}
#pragma warning restore 1591
